[package]
name = "jruff_java_cst"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[lib]
doctest = false

[dependencies]
jruff_java_parser = { path = "../jruff_java_parser" }
jruff_text_size = { path = "../jruff_text_size" }
tree-sitter = "0.24"

[dev-dependencies]
