[package]
name = "jruff_checkstyle"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[lib]
doctest = false

[dependencies]
quick-xml = { version = "0.37", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
