[package]
name = "lintal_java_cst"
version = "0.1.6"
edition = "2024"
rust-version = "1.92"
license = "MIT"

[lib]
doctest = false

[dependencies]
lintal_java_parser = { path = "../lintal_java_parser" }
lintal_text_size = { path = "../lintal_text_size" }
tree-sitter = "0.26"

[dev-dependencies]
